name: Waka Readme

on:
  schedule:
    # Runs at 7am Taipei Time (UTC+8), which is 11pm UTC
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@dbb6bd8a1dd037cffb5c80eedf46e70896eadfc8
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false
